language: rust
os: windows
rust:
    - stable
    - beta
    - nightly
jobs:
    allow_failures:
        - rust: nightly
    fast_finish: true
script:
    - cargo build --verbose --release
deploy:
    provider: releases
    api_key: $GITHUB_TOKEN
    file: "target/release/aarchitect.exe"
    on:
        tags: true

