name: Rust

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

env:
  CARGO_TERM_COLOR: always

jobs:
  skip-ci-check:
    runs-on: windows-latest
    
    outputs:
      skip: ${{ steps.skip-ci.outputs.skip }}
      
    steps:
      - name: Skip Workflow
        id: skip-ci
        uses: saulmaldonado/skip-workflow@v1.1.0
        with:
          phrase: '[skip ci]'
          github-token: ${{ secrets.GITHUB_TOKEN }}


  windows-build:
    name: Windows Build
    needs: skip-ci-check
    
    if: ${{ !needs.skip-ci-check.outputs.skip }}
    runs-on: windows-2019
    
    steps:
    - uses: actions/checkout@v2
    - name: Build
      if: ${{ !steps.skip-workflow.outputs.skip }}
      run: cargo build --verbose --release
      
    - uses: actions/upload-artifact@v2
      name: Upload artifacts
      if: ${{ !steps.skip-workflow.outputs.skip }}
      with:
        name: aarchitect
        path: target/release/aarchitect.exe
        
  darwin-build:
    name: macOS build
    if: ${{ !needs.skip-ci-check.outputs.skip }}
    runs-on: macos-latest
    
    steps:
      - name: Install Rust Nightly
        if: ${{ !steps.skip-workflow.outputs.skip }}
        run: rustup toolchain install nightly && rustup default nightly
      
      - uses: actions/checkout@v2
      - name: Build
    
        if: ${{ !steps.skip-workflow.outputs.skip }}
        run: cargo build --verbose --release
      
      - uses: actions/upload-artifact@v2
        name: Upload artifacts
        if: ${{ !steps.skip-workflow.outputs.skip }}
        with:
          name: aarchitect
          path: target/release/*.dmg
    
  
