name: Rust

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

env:
  CARGO_TERM_COLOR: always

# might change windows to macOS.
jobs:
  skip-ci-check:
    runs-on: windows-latest
    
    outputs:
      skip: ${{ steps.skip-ci.outputs.skip }}
      
    steps:
      - name: Skip Workflow
        id: skip-ci
        uses: saulmaldonado/skip-workflow@v1.1.0
        with:
          phrase: '[skip ci]'
          github-token: ${{ secrets.GITHUB_TOKEN }}


  build:
    needs: skip-ci-check
    
    if: ${{ !needs.skip-ci-check.outputs.skip }}
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Build
      if: ${{ !steps.skip-workflow.outputs.skip }}
      run: cargo build --verbose --release
      
    - uses: actions/upload-artifact@v2
      name: Upload artifacts
      if: ${{ !steps.skip-workflow.outputs.skip }}
      with:
        name: aarchitect
        path: target/release/aarchitect.exe
    
  
