name: Rust

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        ext: " "
        include:
        - os: windows-latest
          ext: ".exe"
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
      
    - uses: actions/upload-artifact@v2
      name: Upload artifacts
      with:
        name: aarchitect
        path: target/debug/aarchitect${{ matrix.ext }}
    
  
