name: Rust

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Skip Workflow
      uses: saulmaldonado/skip-workflow@v1.1.0
      with:
        phrase: "[skip-ci]"
        fail-fast: true

    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose --release
      
    - uses: actions/upload-artifact@v2
      name: Upload artifacts
      with:
        name: aarchitect
        path: target/release/aarchitect.exe
    
  
